### ISSUE TITLE
Webdriver fingerprint fails

### ISSUE THREAD

**Issue by erikyo** [antoinevastel/fp-collect#12]
https://github.com/antoinevastel/fp-collect/blob/7963703e97784cd228af35dbce4785c5da0427e2/src/fpCollect.js#L230-L233

I believe the reason why some users reports about failing tests (https://github.com/antoinevastel/fpscanner/issues/8) are probably related to [webdriver](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver) that is a property of window.navigator and not of window.

From my tests it is the only one that fails on a real browser but it is important to fix it because it is exactly what is needed whether the user agent is controlled by automation

**Comment by antoinevastel** [comment]
Hi @erikyo , thanks for your remark. Because of my current position at DataDome (a bot detection company), I won't update this library.
I can just tell you that when I wrote this library, navigator.webdriver didn't exist on non-automated Chrome. Nowadays (but probably for > 2 years), navigator.webdriver = false even on non automated browser.

**Comment by erikyo** [comment]
However, congratulations on your research... really brilliant!
